[build]
# dockerfile = "./docker/linux-cross/Dockerfile"
# pre-build = [
#     "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable",
#     ". $HOME/.cargo/env",
#     "cargo install --force --locked bindgen-cli && mv $HOME/.cargo/bin/bindgen /usr/bin",
#     "rm -rf $HOME/.cargo"
# ]
# pre-build = [
#     "apt update",
#     "apt install --assume-yes --no-install-recommends build-essential llvm-8-dev libclang-8-dev clang-8",
# ]

[build.env]
passthrough = ["RUSTFLAGS"]

# MIPS targets are dropped to Tier 3
# https://github.com/rust-lang/compiler-team/issues/648
# FIXME: build-std with sequence is supported only on git
[target.mips-unknown-linux-gnu]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mips-unknown-linux-musl]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mips64-unknown-linux-gnuabi64]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mips64-unknown-linux-muslabi64]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mips64el-unknown-linux-gnuabi64]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mips64el-unknown-linux-muslabi64]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mipsel-unknown-linux-gnu]
build-std = ["std", "panic_abort", "proc_macro"]
[target.mipsel-unknown-linux-musl]
build-std = ["std", "panic_abort", "proc_macro"]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos"
# GCC 4.8.2 doesn't support ACLE
# https://github.com/briansmith/ring/issues/1728
# [target.aarch64-unknown-linux-gnu]
# image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main-centos"
